name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    container: electronuserland/builder:wine

    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          USE_HARD_LINKS: false
