name: Release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:mac
      - run: npm run build:linux
        env:
          USE_HARD_LINKS: false
      - name: Upload macos binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/Future Prospect-*-*.zip
          file_glob: true
