name: Release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ${{ matrix.os }}
    container: electronuserland/builder:wine

    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:all
        env:
          USE_HARD_LINKS: false
      - name: Upload macos binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/future-prospect-*-mac.zip
          file_glob: true
